### ISSUE TITLE
In Generators & Coroutines.ipynb, is threading really used for CPU bound tasks?

### ISSUE THREAD

**Issue by gitgithan** [ldo/python_topics_notebooks#1]
> main situation where you cannot avoid threading is when you are performing some CPU-intensive task that can benefit from running on multiple CPUs in parallel. If your problem is not CPU-bound but is I/O-bound, then threads don’t buy you anything

Any explanations on why this statement is true? 
I see many sources saying multhreading is a solution to IO bound tasks and multiprocessing for CPU bound, but the above statement is saying the opposite

**Comment by ldo** [comment]
Feel free to offer a demonstration of why it is not.

Multithreading and multiprocessing are just different ways of organizing CPU-bound tasks.
